---
- name: Update all packages to latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  when: utils_update_packages

- name: Install addititonal packages
  ansible.builtin.apt:
    name: "{{item}}"
    state: latest
    update_cache: true
  loop: "{{utils_packages}}"