---
argument_specs:
  main:
    description: >
      Role that different utils on server
    options:
      utils_packages:
        type: list
        elements: str
        description: List of packages that will be installed on server
      utils_update_packages:
        type: bool
        default: true
        description: Whether update packages or not